App/urls.py
from django.urls import path
from App.views import *

urlpatterns = [
    
    # VBC              
    path('equipos/', EquipoListView.as_view(), name="equipos"),
    path('nuevo_equipo/', EquipoCreateView.as_view(), name="nuevo_equipo"),
    path('editar_equipo/<int:pk>', EquipoUpdateView.as_view(), name="editar_equipo"),
    path('eliminar_equipo/<int:pk>', EquipoDeleteView.as_view(), name="eliminar_equipo"),
    path('ver_equipo/<int:pk>', EquipoDetailView.as_view(), name="ver_equipo"),

    # Se reemplazan por las anteriores 
    # path('crear_equipo/', crear_equipo, name="crear_equipo"),
    # path('grabar_equipo/', grabar_equipo, name="grabar_equipo"),
    # path('actualizar_equipo/<id_equipo>', actualizar_equipo, name="actualizar_equipo"),

    path('partidos/', PartidoListView.as_view(), name="partidos"),
    path('crear_partido/', crear_partido, name="crear_partido"),
    path('grabar_partido/', grabar_partido, name="grabar_partido"),
    path('actualizar_partido/<int:pk>', actualizar_partido, name="actualizar_partido"),
    path('eliminar_partido/<int:pk>', eliminar_partido, name="eliminar_partido"),
    path('ver_partido/<int:pk>', ver_partido, name="ver_partido"),
    
    path('resultados/', ResultadoListView.as_view(), name="resultados"),
    path('crear_resultado/', crear_resultado, name="crear_resultado"),
    path('grabar_resultado/', grabar_resultado, name="grabar_resultado"),
    path('actualizar_resultado/<int:pk>', actualizar_resultado, name="actualizar_resultado"),
    path('eliminar_resultado/<int:pk>', eliminar_resultado, name="eliminar_resultado"),
    path('ver_resultado/<int:pk>', ver_resultado, name="ver_resultado"),

    path('get_resultado/', get_resultado, name="get_resultado"),
    path('buscar_resultado/', buscar_resultado, name="buscar_resultado"),

    path('posiciones/', PosicionListView.as_view(), name="posiciones"),
    path('crear_posicion/', crear_posicion, name="crear_posicion"),
    path('grabar_posicion/', grabar_posicion, name="grabar_posicion"),
    path('actualizar_posicion/<int:pk>', actualizar_posicion, name="actualizar_posicion"),
    path('eliminar_posicion/<int:pk>', eliminar_posicion, name="eliminar_posicion"),
    path('ver_posicion/<int:pk>', ver_posicion, name="ver_posicion"),
    

    path("login/",iniciar_sesion, name="login"),
    path("registrarse/",registrarse, name="registrarse"),
    path("cerrar_sesion/",cerrar_sesion, name="cerrar_sesion"),
    path("edit/", editarPerfil, name="Editar Usuario"),
    path("contra/", CambiarContra.as_view(), name="Cambiar Contraseña"),
    path("avatar/", agregar_avatar, name="Agregar Avatar"),

    path("aboutme/",aboutme, name="aboutme"),
    
    path('', home, name="home"),
]

PreEntrega3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("App/", include("App.urls") ), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto_Final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("App/", include("App.urls") ), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from django.contrib.auth.models import User 

class Equipos(models.Model):
    nombre = models.CharField(max_length=30)
    fechafundacion = models.DateField()

    def __str__(self):
        return f"{self.nombre}"

class Partidos(models.Model):
    equipo_local = models.ForeignKey(Equipos, name="equipo_local", on_delete=models.SET_NULL, null=True, related_name='equipo_local')
    equipo_visitante = models.ForeignKey(Equipos, name="equipo_visitante", on_delete=models.SET_NULL, null=True, related_name='equipo_visitante')
    fecha = models.DateField()
    hora = models.TimeField()

    def __str__(self):
        return f"{self.equipo_local} VS {self.equipo_visitante}"

class Resultados(models.Model):
    partido = models.ForeignKey(Partidos, on_delete=models.SET_NULL, null=True)
    equipo_local = models.IntegerField()
    equipo_visitante = models.IntegerField()

    def __str__(self):
        return f"{self.equipo_local} - {self.equipo_visitante} "

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)
    def __str__(self):
        return f"{self.user} - {self.imagen}"
    
class Posiciones(models.Model):
    equipo = models.ForeignKey('Equipos', on_delete=models.SET_NULL, null=True)
    puntos = models.IntegerField()
    def __str__(self):
        return f"{self.equipo} - {self.puntos}"

App/templates/aboutme.html
{% extends "home.html" %}

{% block section %}

    <section class="page-section bg-primary text-white mb-0" id="about">
        <div class="container">
            <!-- About Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-white">About Me</h2>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><svg class="svg-inline--fa fa-star" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"></path></svg><!-- <i class="fas fa-star"></i> Font Awesome fontawesome.com --></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- About Section Content-->
            <div class="row">
                <div class="col-lg-4 ms-auto">
                    <p class="lead">
                        Soy Sebastián. Soy Analista de Sistemas. Trabajo como Desarrollador Full Stack.
                        Soy un profesional con más de 10 años de experiencia en el campo de sistemas informáticos y tecnología.
                        Tengo facilidad para trabajar tanto en equipo como de forma independiente, según las necesidades
                    </p>
                </div>
                <div class="col-lg-4 me-auto">
                    <p class="lead">
                        Actualmente me encuentro capacitandomé en el lenguaje Python con la intención de lograr trabajar en proyectos con 
                        este lenguaje y frameworks como Django. Hoy en día el lenguaje que utilizo es PHP.
                    </p>
                </div>
            </div>
            <!-- About Section Button
            <div class="text-center mt-4">
                <a class="btn btn-xl btn-outline-light" href="https://startbootstrap.com/theme/freelancer/">
                    <svg class="svg-inline--fa fa-download me-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="download" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M288 32c0-17.7-14.3-32-32-32s-32 14.3-32 32V274.7l-73.4-73.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l128 128c12.5 12.5 32.8 12.5 45.3 0l128-128c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L288 274.7V32zM64 352c-35.3 0-64 28.7-64 64v32c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V416c0-35.3-28.7-64-64-64H346.5l-45.3 45.3c-25 25-65.5 25-90.5 0L165.5 352H64zm368 56a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"></path></svg>
                    Free Download!
                </a>
            </div>
            -->
        </div>
    </section>

{% endblock %}

App/templates/crear_resultado.html
{% extends "home.html" %}

{% block section %}

    <h1>Crear Resultado</h1>

    <form action="/App/grabar_resultado/" method="POST"> 
        
        {% csrf_token %}
       
        <p>
            Partido : 
            <select name="partidos">
                <option value=""></option>
                {% for partido in partidos %}
                    <option value="{{partido.id}}">
                        {{ partido.fecha }} - {{ partido.hora }} {{ partido.equipo_local.nombre }} vs {{ partido.equipo_visitante.nombre }}
                    </option>
                {% endfor %}
            </select>
        </p>
        
        
        <p>
            Equipo Local : <input type="number" name="equipo_local" min="0" max="10">  
        </p>

        <p>
            Equipo Visitante : <input type="number" name="equipo_visitante" min="0" max="10"> 
        </p>
        
        <p>
            <input type="submit" value="Guardar"> 
        </p>

    </form>

{% endblock %}

App/templates/get_resultado.html
{% extends "home.html" %}

{% block section %}

    <h1>Resultado </h1>

    <p>
        Equipo Local : <input type="number" name="equipo_local" min="0" max="10" value="{{ resultado.equipo_local }}" class="form-control" readonly>  
    </p>

    <p>
        Equipo Visitante : <input type="number" name="equipo_visitante" min="0" max="10" value="{{ resultado.equipo_visitante }}" class="form-control" readonly> 
    </p>
        
{% endblock %}

App/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Torneo</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/football-157930_1280.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    Torneo
                </a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'equipos' %}">Equipos</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'partidos' %}">Partidos</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'resultados' %}">Resultados</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'posiciones' %}">Posiciones</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'buscar_resultado' %}">Buscar Resultado</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.is_authenticated %}
                                    {% if user.avatar_set.last %}
                                        <img src="{{user.avatar_set.last.imagen.url}}" width="50px" height="50px" alt="" style="border-radius: 25px;">
                                    {% else %}
                                        <img src="{% static 'assets/img/avatar-defecto.jpg' %}" width="50px" height="50px" alt="" style="border-radius: 25px;">
                                    {% endif %} 
                                {% else %}   
                                    <img src="{% static 'assets/img/avatar-defecto.jpg' %}" width="50px" height="50px" alt="" style="border-radius: 25px;">
                                {% endif %} 
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <b>{{user.first_name}} {{user.last_name}}</b>
                                        </a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'Editar Usuario' %}">Editar mi Cuenta</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'Agregar Avatar' %}">Cambiar Avatar</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'Cambiar Contraseña' %}">Cambiar Password</a>
                                    </li>  

                                    <li><hr class="dropdown-divider"></li>
                                
                                    <li>
                                        <a class="dropdown-item" href="{% url 'cerrar_sesion' %}">Cerrar Sesión</a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'registrarse' %}">Registrarse</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'login' %}">Iniciar Sesión</a>
                                    </li>
                                {% endif %} 
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-2">Torneo</h1>
                
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mt-4" src="{% static 'assets/img/football-157930_1280.png' %}" alt="..." 
                    style="width: 120px; height: 120px;"
                />
                
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">

                    <h3>{{ mensaje }}</h3>
                    
                    {% block section %}
  
                    {% endblock %}
                </p>
            </div>
        </header>
        
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Localización</h4>
                        <p class="lead mb-0">
                            Bhaía Blanca
                            <br />
                            Bs As, Argentina
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Redes Sociales</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">Acerca de Mi</h4>
                        <p class="lead mb-0">
                            Un poco de información personal..
                            <a target="_blank" class="btn btn-outline-light btn-social mx-1" href="https://www.linkedin.com/in/sebasti%C3%A1n-d%C3%ADaz-aa938a105/">
                                <i class="fab fa-fw fa-linkedin-in"></i>
                            </a>
                            <a href="{% url 'aboutme' %}">Conóceme</a>
                            
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Your Website 2024</small></div>
        </div>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" ></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>